#!/bin/bash

##############长期活动##############
# 签到
node jd_bean_sign.js
# 东东超市兑换奖品
node jd_blueCoin.js
# 摇京豆
node jd_club_lottery.js
# 东东农场
node jd_fruit.js
# 宠汪汪
node jd_joy.js
# 宠汪汪喂食
node jd_joy_feedPets.js
# 宠汪汪积分兑换奖品
node jd_joy_reward.js
# 宠汪汪偷好友积分与狗粮
node jd_joy_steal.js
# 摇钱树
node jd_moneyTree.js
# 东东萌宠
node jd_pet.js
# 京东种豆得豆
node jd_plantBean.js
# 京东全民开红包
node jd_redPacket.js
# 进店领豆
node jd_shop.js
# 京东天天加速
node jd_speed.js
# 东东超市
node jd_superMarket.js
# 取关京东店铺商品
node jd_unsubscribe.js
# 京豆变动通知
node jd_bean_change.js
# 京东抽奖机
node jd_lotteryMachine.js
# 京东排行榜
node jd_rankingList.js
# 天天提鹅
node jd_daily_egg.js
# 金融养猪
node jd_pigPet.js
# 点点券
node jd_necklace.js
# 京喜工厂
node jd_dreamFactory.js
# 东东小窝
node jd_small_home.js
# 东东工厂
node jd_jdfactory.js
# 十元街
node jd_syj.js
# 京东快递签到
node jd_kd.js
# 京东汽车(签到满500赛点可兑换500京豆)
node jd_car.js
# 领京豆额外奖励(每日可获得3京豆)
node jd_bean_home.js
# 京东直播(每日18豆)
node jd_live.js
# 微信小程序京东赚赚
node jd_jdzz.js
# 宠汪汪邀请助力
node jd_joy_run.js
# 注销京东已开的店铺会员，不是注销京东plus会员，个别店铺无法注销
node jd_unbind.js
# crazyJoy自动每日任务
node jd_crazy_joy.js
# 京东汽车旅程赛点兑换金豆
node jd_car_exchange.js
# 导到所有互助码
node jd_get_share_code.js
# 口袋书店
node jd_bookshop.js
# 京喜农场
node jd_jxnc.js
# 签到领现金
node jd_cash.js
# 京喜app签到
node jx_sign.js
# 京东家庭号(暂不知最佳cron)
node jd_family.js
# 闪购盲盒
node jd_sgmh.js
# 源头好物红包
node jd_coupon.js
# 京东手机年终奖
node jd_festival.js
# 盲盒抽京豆
node jd_mh.js
# 京东秒秒币
node jd_ms.js
# 小鸽有礼
node jd_xg.js
# 京东超级盒子
node jd_super_box.js
